{
    'name': 'Custom LMS',
    'version': '18.0.1.0.0',
    'summary': 'Learning Management System for Odoo',
    'category': 'Education',
    'author': 'Custom',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'website',
        'portal',
        'mail',
        'website_slides',
    ],
    'data': [
        'security/groups.xml',
        'security/record_rules.xml',
        'security/ir.model.access.csv',
        'views/course_views.xml',
        'views/lesson_views.xml',
        'views/announcement_views.xml',
        'views/enrollment_views.xml',
        'views/quiz_views.xml',
        'views/portal_templates.xml',
        'views/website_templates.xml',
        'views/website_menu.xml',
        'views/website_homepage.xml',
    ],
    'application': True,
    'installable': True,
}
